### PR TITLE
3 namespace setup amq sample app

### PR DESCRIPTION
**Pull request by Danil-Grigorev**
Sample 3 namespace setup for AMQ test application.

Namespace:
`amq_core` - contains template, broker and configmaps.
`amq_consumer`
`amq_producer`

communicating via `*svc.cluster.local`.

client-setup(1)

### CODE REVIEW

**Comment by jwmatthews** [comment]
Please add:
 - info to mig-demo-apps/README.md for amq-app similar to the other examples.
 - a README.md in apps/amq-app/README.md with some info like other examples of how to deploy and use, lets expand this info to give more background of what is being deployed and how to verify it's working


I ran deploy.sh and have 3 namespaces created, unsure if the app is running correctly I see this error in logs that seems bad:

```
23:34:10.968 [ActiveMQ Task-1] WARN  o.a.a.t.failover.FailoverTransport - Failed to connect to [tcp://amq-broker-ssl-amq-tcp.amq-core.svc.cluster.local:61616] after: 10 attempt(s) continuing to retry.
23:34:10.968 [ActiveMQ Task-1] WARN  o.a.a.t.failover.FailoverTransport - Failed to connect to [tcp://amq-broker-ssl-amq-tcp.amq-core.svc.cluster.local:61616] after: 10 attempt(s) continuing to retry.
```

**Comment by Danil-Grigorev** [comment]
The changes you requested were included with latest commit. @jwmatthews, @jortel Please (re)review so the CI part could be done with existing state of the app.

**Comment by jwmatthews** [comment]
@Danil-Grigorev fyi @pranavgaikwad will help on reviewing and getting this merged

**Comment by pranavgaikwad** [comment]
Looking good after the latest changes. I was able to deploy without issues. If you already deployed this app on your cluster, you may want to destroy everything. bring state to clean and re-deploy with latest changes, it should work!

**Pull request merged**
